// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WinStrideApi.Data;

#nullable disable

namespace WinStride_Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260222230348_AddNetworkConnectionsTable")]
    partial class AddNetworkConnectionsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WinStrideApi.Models.Heartbeat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsAlive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Heartbeats");
                });

            modelBuilder.Entity("WinStrideApi.Models.TCPView", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("LocalAddress")
                        .HasColumnType("text");

                    b.Property<int?>("LocalPort")
                        .HasColumnType("integer");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModuleName")
                        .HasColumnType("text");

                    b.Property<int?>("ProcessId")
                        .HasColumnType("integer");

                    b.Property<string>("ProcessName")
                        .HasColumnType("text");

                    b.Property<string>("Protocol")
                        .HasColumnType("text");

                    b.Property<long>("RecvBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("RecvPackets")
                        .HasColumnType("bigint");

                    b.Property<string>("RemoteAddress")
                        .HasColumnType("text");

                    b.Property<int?>("RemotePort")
                        .HasColumnType("integer");

                    b.Property<long>("SentBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("SentPackets")
                        .HasColumnType("bigint");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("TimeCreated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("MachineName", "TimeCreated")
                        .IsDescending(false, true);

                    b.ToTable("WinNetworkConnections", (string)null);
                });

            modelBuilder.Entity("WinStrideApi.Models.WinEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EventData")
                        .HasColumnType("jsonb");

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<string>("Level")
                        .HasColumnType("text");

                    b.Property<string>("LogName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("TimeCreated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("TimeCreated")
                        .IsDescending();

                    b.HasIndex("LogName", "TimeCreated")
                        .IsDescending(false, true);

                    b.ToTable("WinEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
